# Generated by Django 5.2.3 on 2025-06-28 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recurringmessage',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='recurringmessage',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='recurringmessage',
            name='custom_body',
        ),
        migrations.RemoveField(
            model_name='recurringmessage',
            name='custom_title',
        ),
        migrations.RemoveField(
            model_name='recurringmessage',
            name='interval_days',
        ),
        migrations.RemoveField(
            model_name='recurringmessage',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='recurringmessage',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='recurringmessage',
            name='interval_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='recurringmessage',
            name='interval_type',
            field=models.CharField(choices=[('minutes', 'Minutes'), ('hours', 'Hours'), ('days', 'Days'), ('weeks', 'Weeks')], default='days', max_length=10),
        ),
    ]
